title:            yellowstar
description:      Being a web developer.
url:              http://huangxingxing.info
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          yellowstar # Your name.
disqus_shortname: huangxingxing # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: UA-45822478-1  # set tracking, UA-XXXX-Y.

links:
  - name:         关于我
    url:          /about
  - name:         联系我
    url:          /contact
  - name:         Twitter
    url:          http://twitter.com/yellowstar520
    external:     true
  - name:         GitHub
    url:          http://github.com/hxx/scribble
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
